# Generated by Django 5.2.4 on 2025-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='name',
            new_name='nombre',
        ),
    ]
